# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{structr}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Suschlik"]
  s.date = %q{2009-12-07}
  s.email = %q{peter-structr@suschlik.de}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/invoice.rb",
     "examples/top.rb",
     "lib/structr.rb",
     "structr.gemspec",
     "test/helper.rb",
     "test/test_field_descriptor.rb",
     "test/test_structr.rb"
  ]
  s.homepage = %q{http://github.com/splattael/structr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Parse plain text to Ruby classes.}
  s.test_files = [
    "test/test_field_descriptor.rb",
     "test/test_structr.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<riot>, ["= 0.10.1"])
      s.add_development_dependency(%q<riot_notifier>, ["= 0.0.1"])
    else
      s.add_dependency(%q<riot>, ["= 0.10.1"])
      s.add_dependency(%q<riot_notifier>, ["= 0.0.1"])
    end
  else
    s.add_dependency(%q<riot>, ["= 0.10.1"])
    s.add_dependency(%q<riot_notifier>, ["= 0.0.1"])
  end
end

